### ISSUE TITLE
Return non 0 exit code if goodcheck detect

### ISSUE THREAD

**Issue by issei126** [sider/goodcheck#24]
I want the check command  to return non 0 exit code if it detect a pattern.
I want to  divide processing by exit code.

I think the error option like misspell is good.
https://github.com/client9/misspell

Regards.

**Comment by soutaro** [comment]
Sounds good. 💪
The feature will be implemented soon.

**Comment by ybiquitous** [comment]
Nice idea! 👍 

In addition, how about having two error codes?

For example, ESLint has 3 exit codes:
- `0`: Linting was successful and there are no linting errors.
- `1`: Linting was successful and there is at least one linting error.
- `2`: Linting was unsuccessful due to a configuration problem or an internal error.

See https://eslint.org/docs/user-guide/command-line-interface#exit-codes

**Comment by pocke** [comment]
> For example, ESLint has 3 exit codes:

I think we should not use ESLint's exit code rule without any changes. In other words, we need to modify the rule. It is confusing because Ruby exits 1 if Ruby raises some error. Therefore we cannot differentiate internal error from linting error if we decide linting error status is 1.


I think goodcheck should not use exit code 1 as linting error. For example, I recommend the following rule.

* 0: No internal errors, and no linting errors.
* 1: Undefined. goodcheck may exit with 2 when an error is unhandled.
* 2: No internal errors, but it has at least one linting error.
* 3: Internal errors.

FYI,  you can also use [sysexits](https://github.com/ged/sysexits), but I think it is too complicated, so I think goodcheck does not need it.
HAML-Lint [uses sysexits](https://github.com/brigade/haml-lint/blob/a5bcfa3040888eda77f70e77031c2b25c2db19db/lib/haml_lint/cli.rb), but I'm not sure we need it.

**Comment by pocke** [comment]
> On the other hand, I think that to distinguish 1 and 3 may confuse Goodcheck users, what do you think about this?



Yes, I agree. It is probably confusing.

I have the opinion for usage of exit status 1, but I think exit status 3 is optional feature (maybe it is over-engineering).
I guess almost users do not want to distinguish unhandled error from handled errors by exit status. Therefore we can merge status 3 to status 1.

Sorry for my confusing reply.

**Comment by issei126** [comment]
Thank you for implement !
I use newest goodcheck now.

**Comment by ybiquitous** [comment]
@issei126 Thanks so much for your suggestion! 😄
